### ISSUE TITLE
Why it has archive function twice ?

### ISSUE THREAD

**Issue by Dasinfomedia2** [nowendwell/laravel-archivable#1]
1. You have `public function archive()` in trait 

2. You have same function as builder macro.In the Scope file
```
$builder->macro('archive', function (Builder $builder) {
            return $builder->update([$builder->getModel()->getArchivedAtColumn() => Carbon::now()]);
        });
```
While it will only call the function of the trait so why it's needed in the builder macro?
Can you please explain? that will be very helpful.
Thanks

**Comment by modernben** [comment]
Hi there. The trait will be available on a single instance of a model while the macro on the builder will be available via the query builder.

Trait
$user = User::first();
$user->archive();

Macro
User::where('id', <, 10)->archive();

**Comment by Dasinfomedia2** [comment]
Thanks.
